name: Auto Claim Humanity Reward

on:
  schedule:
    - cron: '0 */9 * * *'  # Every 9 hours
  workflow_dispatch:  # Can also be triggered manually from GitHub UI

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file from secrets
        run: |
          echo "PRIVATE_KEY=${{ secrets.PRIVATE_KEY }}" >> .env
          echo "WALLET_ADDRESS=${{ secrets.WALLET_ADDRESS }}" >> .env
          echo "RPC_URL=${{ secrets.RPC_URL }}" >> .env

      - name: Run claim reward
        run: python main.py
